// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByFDRr4SVWR2Yo16EB_3nMwEDdcK1-Q9w',
    appId: '1:917641802576:web:1570d2225977daf6217255',
    messagingSenderId: '917641802576',
    projectId: 'hackathoneproject-915ff',
    authDomain: 'hackathoneproject-915ff.firebaseapp.com',
    storageBucket: 'hackathoneproject-915ff.appspot.com',
    measurementId: 'G-XWDECB1ZNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD140905NRW8ZoApGnUz58x6ZEMhK2sx_8',
    appId: '1:917641802576:android:9d9765cdd1451988217255',
    messagingSenderId: '917641802576',
    projectId: 'hackathoneproject-915ff',
    storageBucket: 'hackathoneproject-915ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmwe2PNjkBqSXyqgIiH2uo6kbQdb7JAQg',
    appId: '1:917641802576:ios:7477e12528a495a6217255',
    messagingSenderId: '917641802576',
    projectId: 'hackathoneproject-915ff',
    storageBucket: 'hackathoneproject-915ff.appspot.com',
    iosClientId: '917641802576-dp3ggtbcjmu9b5cnv2h2bkjefh6masn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathoneproject',
  );
}
