import 'package:flutter/material.dart';

List<Map> cardItem = [
  {
    'title':'Peperomia',
    'subTitle': 'Air Purifier',
    'pugImage': 'assets/Group66.png',
    'price': '\$400',
    'isFavorite': false,
    'addCart': 'assets/Group61.png',
    'product': 'assets/PeperomiaObtusfolia.png',
    'lines': 'assets/lines.png',
    "color": const Color(0xff9CE5CB),
  },
  {
    'title':'Watermelon..',
    'subTitle': 'Air Purifier',
    'pugImage': 'assets/Group66.png',
    'price': '\$350',
    'isFavorite': false,
    'addCart': 'assets/Group61.png',
    'product': 'assets/sage.png',
    'lines': 'assets/lines.png',
    "color": const Color(0xffFFE899),
  },
  // {    
  //   'product': 'assets/Group81.png'
  // },
  {
    'title':'Croton Petra',
    'subTitle': 'Air Purifier',
    'pugImage': 'assets/Group66.png',
    'price': '\$200',
    'isFavorite': false,
    'addCart': 'assets/Group61.png',
    'product': 'assets/interiormediumlight.png',
    'lines': 'assets/lines.png',
    "color": const Color(0xff56D1A7),
  },
  {
    'title':'Bird’s Nest Fern',
    'subTitle': 'Air Purifier',
    'pugImage': 'assets/Group66.png',
    'price': '\$160',
    'isFavorite': false,
    'addCart': 'assets/Group61.png',
    'product': 'assets/Layer8.png',
    'lines': 'assets/lines.png',
    "color": const Color(0xffB2E28D),
  },
  {
    'title':'Cactus',
    'subTitle': 'Air Purifier',
    'pugImage': 'assets/Group66.png',
    'price': '\$260',
    'isFavorite': false,
    'addCart': 'assets/Group61.png',
    'product': 'assets/MaskGroup.png',
    'lines': 'assets/lines.png',
    "color": const Color(0xffDEEC8A),
  },
  {
    'title':'Aloe Vera',
    'subTitle': 'Air Purifier',
    'pugImage': 'assets/Group66.png',
    'price': '\$210',
    'isFavorite': false,
    'addCart': 'assets/Group61.png',
    'product': 'assets/Layer27.png',
    'lines': 'assets/lines.png',
    "color": const Color(0xffF5EDA8),
  },
  {
    'title':'Peperomia',
    'subTitle': 'Air Purifier',
    'pugImage': 'assets/Group66.png',
    'price': '\$400',
    'isFavorite': false,
    'addCart': 'assets/Group61.png',
    'product': 'assets/PeperomiaObtusfolia.png',
    'lines': 'assets/lines.png',
    "color": const Color(0xff9CE5CB),
  },
];